# Generated by Django 5.2.11 on 2026-03-02 20:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='İşletme adı')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
                ('working_hours', models.JSONField(blank=True, default=dict, verbose_name='Çalışma saatleri')),
                ('booking_settings', models.JSONField(blank=True, default=dict, verbose_name='Randevu ayarları')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'İşletme',
                'verbose_name_plural': 'İşletmeler',
            },
        ),
    ]
