# Generated by Django 6.0.1 on 2026-03-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Beklemede'), ('PAID', 'Ödendi'), ('TRIAL', 'Deneme')], default='PENDING', max_length=20, verbose_name='Ödeme durumu'),
        ),
        migrations.AddField(
            model_name='business',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deneme bitiş tarihi'),
        ),
    ]
