# Generated by Django 5.2.11 on 2026-03-02 20:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Hizmet adı')),
                ('duration_min', models.PositiveIntegerField(verbose_name='Süre (dakika)')),
                ('price_try', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat (₺)')),
                ('active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.business')),
            ],
            options={
                'verbose_name': 'Hizmet',
                'verbose_name_plural': 'Hizmetler',
            },
        ),
    ]
